---
title: "Chapter 4: Vector Applications"
output: html_document
date: "`r Sys.Date()`"
---

## Code Exercises

Correlation Exercises

Exercise 4-1.

Write a function that takes two vectors as input and provides two numbers as
output: the Pearson correlation coefficient and the cosine similarity value.

```{r}
v1 <- runif(50)
v2 <- runif(50)

normv <- function(v) {
    return( v^2 |> sum() |> sqrt() )
}

relation <- function(v1, v2) {
    v1c <- v1 - mean(v1)
    v2c <- v2 - mean(v2)
    p <- (v1c %*% v2c) / (normv(v1c) * normv(v2c))
    
    cossim <- (v1 %*% v2) / (normv(v1) * normv(v2))
    
    return(c(p,cossim))
}

relation(v1,v2)

cor.test(x = v1, y = v2)
coop::cosine(x = v1, y = v2)
```

Exercise 4-2.

```{r}
library(tidyr)
library(ggplot2)
```


```{r}
v1 <- 0:3
offsets <- -50:50
result <- matrix(nrow = 101, ncol = 3)
for (i in 1:length(offsets)) {
    v2 <- v1 - offsets[i]
    result[i,] <- append(relation(v1, v2), offsets[i])
}
```

```{r}
data <- as.data.frame(result)
colnames(data) <- c("r", "c", "offset")
data <- data |>
    pivot_longer(!offset, names_to = "type", values_to = "r or c")
ggplot(data = data, aes(x = offset, y = `r or c`, shape = type)) +
    geom_line() +
    geom_point()
```

Exercise 4-4.

```{r}
v1 <- runif(50)
v2 <- runif(50)

cor(v1, v2)
```

Filtering and Feature Detection Exercises

Exercise 4-5.

```{r}
kernel <- c(-1, 1)
t <- 0:29
tsignal <- data.frame(t)
tsignal$sig <- c(rep(0,10), rep(1.5,10), rep(0,10))
```

```{r}
ggplot(data = tsignal, aes(x = t, y = sig)) +
    geom_line() +
    geom_point()
```

```{r}
for (i in 1:nrow(tsignal)) {
    tsignal$edge[i] <- tsignal$sig[i : sum(i, 1)] %*% kernel |> as.numeric()
}
tsignal$edge[30] <- tsignal$edge[29]

tsignal <- tsignal |>
    pivot_longer(!t, names_to = "type", values_to = "signal")
```

```{r}
ggplot(data = tsignal, aes(x = t, y = signal, shape = type)) +
    geom_line() +
    geom_point()
```

Exercise 4-6.

```{r}
kernel <- c(0, .1, .3, .8, 1, .8, .3, .1, 0)
nkernel <- kernel * (1/sum(kernel))
plot(nkernel, type = "b")

signal <- rnorm(n = 100)
plot(signal, type = "b")
```

```{r}
signal <- rnorm(100)
kernel <- c(0, .1, .3, .8, 1, .8, .3, .1, 0)
nkernel <- kernel * (1/sum(kernel))
```

```{r}
length <- length(signal) + length(nkernel) - 1
output <- c()
for (i in 1:length) {
    if (i <= length(nkernel)) {
        sig <- head(signal,i)
        k <- tail(nkernel,i)
    }
    else if (i >= length(signal)) {
        sig <- tail(signal,(length(nkernel) - (i - length(signal))))
        k <- head(nkernel, (length(nkernel) - (i - length(signal))))
    }
    else {
        sig <- signal[(i - length(nkernel) + 1) : i]
        k <- nkernel
    }
    output <- append(output, sig %*% k)
}
```

```{r}
plot(signal, type = "b")
plot(output, type = "b")
```

```{r}
ggplot() +
    geom_line(data = as.data.frame(signal), aes(y = signal, x = 1:100), 
              color = "blue") +
    geom_line(data = as.data.frame(output[4:103]), aes(y = output[4:103], x = 1:100), 
              color = "red")
```

Exercise 4-7.

```{r}
signal <- rnorm(100)
kernel <- c(0, .1, .3, .8, -1, .8, .3, .1, 0)
nkernel <- kernel - mean(kernel)
```

```{r}
plot(nkernel, type = "b")
plot(signal, type = "b")
```

```{r}
length <- length(signal) + length(nkernel) - 1
output <- c()
for (i in 1:length) {
    if (i <= length(nkernel)) {
        sig <- head(signal,i)
        k <- tail(nkernel,i)
    }
    else if (i >= length(signal)) {
        sig <- tail(signal,(length(nkernel) - (i - length(signal))))
        k <- head(nkernel, (length(nkernel) - (i - length(signal))))
    }
    else {
        sig <- signal[(i - length(nkernel) + 1) : i]
        k <- nkernel
    }
    output <- append(output, sig %*% k)
}
```

```{r}
plot(signal, type = "b")
plot(output, type = "b")
```

```{r}
ggplot() +
    geom_line(data = as.data.frame(signal), aes(y = signal, x = 1:100), 
              color = "blue") +
    geom_line(data = as.data.frame(output[4:103]), aes(y = output[4:103], x = 1:100), 
              color = "red")
```

k-Means Clustering

```{r}
class <- matrix(data = rnorm(8, sd = 10), ncol = 2)
class <- data.frame(class)
colnames(class) <- c('x','y')
plot(class)
```

```{r}
dist(class, method = "euclidean")
```

```{r}
k <- 5
data <- matrix(data = rnorm(300, sd = 5), ncol = 2) |> data.frame()
colnames(data) <- c('x', 'y')
centid <- sample(nrow(data), size = k, replace = F)
centroids <- data[centid,]
plot(data, col=ifelse(row.names(data) %in% centid, "red", "blue"))
```

```{r}
dists <- matrix(0, nrow = nrow(data), ncol = k)

for (ci in 1:k) {
    dists[,ci] <- apply(data, 1, function(x) sum((x - centroids[ci,])^2))
}
```

```{r}
groupidx <- apply(dists, 1, function(x) which(x == max(x)))
data$groupidx <- groupidx
```

```{r}
for (ki in 1:k) {
    centroids[k,] <- c(mean(data[data$groupidx == ki,'x']), 
                       mean(data[data$groupidx == ki,'y']))
}
```

```{r}
plot(data, col=ifelse(row.names(data) %in% centid, "red", "blue"))
```

```{r}
data <- matrix(data = rnorm(300, sd = 5), ncol = 2) |> data.frame()
colnames(data) <- c('x', 'y')
```


```{r}
iter <- 5

k <- 2


centid <- sample(nrow(data), size = k, replace = F)
centroids <- data[centid,][,1:2]

dists <- matrix(0, nrow = nrow(data), ncol = k)



for (i in 1:iter) {

    for (ci in 1:k) {
        dists[,ci] <- apply(data, 1, function(x) sum((x - centroids[ci,])^2))
    }
    
    groupidx <- apply(dists, 1, function(x) which(x == max(x)))
    data$groupidx <- groupidx
    
    for (ki in 1:k) {
        centroids[k,] <- c(mean(data[data$groupidx == ki,'x']), 
                           mean(data[data$groupidx == ki,'y']))
    }
}

```

```{r}
plot(data[,1:2])
points(centroids, col = "red", pch = 16)
```

```{r}
iter <- 5

k <- 4


centid <- sample(nrow(data), size = k, replace = F)
centroids <- data[centid,][,1:2]

dists <- matrix(0, nrow = nrow(data), ncol = k)

for (i in 1:iter) {
    
    for (ci in 1:k) {
        dists[,ci] <- apply(data, 1, function(x) sum((x - centroids[ci,])^2))
    }
    
    groupidx <- apply(dists, 1, function(x) which(x == max(x)))
    data$groupidx <- groupidx
    
    for (ki in 1:k) {
        centroids[k,] <- c(mean(data[data$groupidx == ki,'x']), 
                           mean(data[data$groupidx == ki,'y']))
    }
}

```


```{r}
plot(data[,1:2])
points(centroids, col = "red", pch = 16)
```